In [9]:
import pandas as pd
import ast


df_pcl = pd.read_csv(
    "dontpatronizeme_pcl.tsv",
    sep="\t",
    header=None,
    skiprows=4,
    names=["par_id", "art_id", "keyword", "country", "text", "label"],
)
train_lbl = pd.read_csv("train_semeval_parids-labels.csv")
dev_lbl = pd.read_csv("dev_semeval_parids-labels.csv")


train_lbl["label_vec"] = train_lbl["label"].apply(ast.literal_eval)
dev_lbl["label_vec"]   = dev_lbl["label"].apply(ast.literal_eval)

train_lbl["y"] = train_lbl["label_vec"].apply(lambda v: int(sum(v) > 0))
dev_lbl["y"]   = dev_lbl["label_vec"].apply(lambda v: int(sum(v) > 0))

In [8]:
train_lbl.head()

   par_id                  label              label_vec  y
0    4341  [1, 0, 0, 1, 0, 0, 0]  [1, 0, 0, 1, 0, 0, 0]  1
1    4136  [0, 1, 0, 0, 0, 0, 0]  [0, 1, 0, 0, 0, 0, 0]  1
2   10352  [1, 0, 0, 0, 0, 1, 0]  [1, 0, 0, 0, 0, 1, 0]  1
3    8279  [0, 0, 0, 1, 0, 0, 0]  [0, 0, 0, 1, 0, 0, 0]  1
4    1164  [1, 0, 0, 1, 1, 1, 0]  [1, 0, 0, 1, 1, 1, 0]  1

In [10]:
df_pcl.head()

,par_id,art_id,keyword,country,text,label
0,1,@@24942188,hopeless,ph,"We 're living in times of absolute insanity , ...",0
1,2,@@21968160,migrant,gh,"In Libya today , there are countless number of...",0
2,3,@@16584954,immigrant,ie,White House press secretary Sean Spicer said t...,0
3,4,@@7811231,disabled,nz,Council customers only signs would be displaye...,0
4,5,@@1494111,refugee,ca,""" Just like we received migrants fleeing El Sa...",0

In [14]:
train = df_pcl.merge(train_lbl[["par_id","y"]], on="par_id", how="inner")
dev   = df_pcl.merge(dev_lbl[["par_id","y"]],   on="par_id", how="inner")


print(train["y"].value_counts())
print(train["label"].value_counts())

y
0    7581
1     794
Name: count, dtype: int64
label
0    6825
1     756
3     369
4     299
2     126
Name: count, dtype: int64